name: Metrics
on:
  # Schedule updates (24 hour cycle)
  schedule:
    - cron: '0 * * * *'
      # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  workflow_call:
    secrets:
      METRICS_TOKEN:
        required: true
      METRICS_TOKEN_WITH_SCOPES:
        required: true
      METRICS_TOKEN_PERSONAL:
        required: true
      PAGESPEED_TOKEN:
        required: true
      GOOGLE_MAP_TOKEN:
        required: true
      SPOTIFY_TOKENS:
        required: true
      STOCK_TOKEN:
        required: true
      TWITTER_TOKEN:
        required: true
      WAKATIME_TOKEN:
        required: true
  push:
    branches:
      # - "test"
      - "main"

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Update metrics
        uses: lowlighter/metrics@latest
        with:
          # Plugin error
          plugins_errors_fatal: no

          # Token
          token: ${{ secrets.METRICS }}

          # Options
          user: sbxte
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Jakarta
          output_action: commit
          committer_branch: data
          committer_message: "chore: update metrics"

          # Achievements
          plugin_achievements: yes
          plugin_achievements_threshold: C
          plugin_achievements_secrets: yes
          plugin_achievements_limit: 0
          plugin_achievements_display: compact

          # Activity
          plugin_activity: yes
          plugin_activity_limit: 8
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_visibility: public

          # Issue and PR follow ups
          plugin_followup: yes
          plugin_followup_sections: repositories, user

          # Habits
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_habits_trim: yes

          # Isometric Calendar
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

          # Languages
          plugin_languages: yes
          # plugin_languages_sections: most-used, recently-used
          plugin_languages_details: lines, bytes-size
          # plugin_languages_threshold: 1%
          plugin_languages_ignored: css, scss, html, php, less
          plugin_languages_indepth: yes
          plugin_languages_analysis_timeout: 15

          # Code changes (lines)
          plugin_lines: yes
          plugin_lines_sections: base, repositories, history

          # People (followers and such)
          plugin_people: yes
          plugin_people_limit: 28
          plugin_people_size: 28
          plugin_people_types: followers, following

          # Stargazers
          # plugin_stargazers: yes
          # plugin_stargazers_charts_type: graph

          # Projects
          plugin_projects: yes
          plugin_projects_limit: 4

          # Notable contributions
          plugin_notable: yes
          plugin_notable_from: all
          plugin_notable_repositories: yes
          plugin_notable_skipped: CancerStop/CancerStop
          plugin_notable_types: commit

          # Reactions
          plugin_reactions: yes
          plugin_reactions_display: absolute
          plugin_reactions_limit: 200
          plugin_reactions_limit_discussions: 100
          plugin_reactions_limit_discussions_comments: 100
          plugin_reactions_limit_issues: 100

          # Traffic
          plugin_traffic: yes

          # Gists
          plugin_gists: yes

          # Topics
          plugin_topics: yes
          plugin_topics_mode: icons
          plugin_topics_sort: stars
          plugin_topics_limit: 0

          # Starred
          plugin_stars: yes
